### PR TITLE
Convert http to ws

### PR DESCRIPTION
**Pull request by rjriel**
This is a PR to solve #306.

I initially was going to just convert the http(s) to ws(s) in the config, but the resulting connection would be inconsistent with the string that was being shown in the URL, so instead I first updated the codebase so all these `engine_url` assignments would happen in one place, then I added the logic to convert. That way the URL shown is consistent with the URL being used to connect.

Happy Hacktoberfest

### CODE REVIEW

**Comment by hrigner** [comment]
👏 Sweet stuff! 🎉
Will test it through on monday!

**Comment by hrigner** [comment]
Works like a charm! :)

It would be nice to have the conversion when entering the engine_url directly in the browser address field as well. Can the magician fix that? :)

**Comment by rjriel** [comment]
Abracadabra!

**Comment by hrigner** [comment]
And don't worry about the coverage/coveralls result, there is some strange stuff happening there 🙀 . You are free to merge :)

**Comment by rjriel** [comment]
I’ll probably do one more commit first, since you created a function for the regex stuff that input fix should probably use it

**Pull request merged**
