### PR TITLE
Low-hanging performance improvements

### PR DESCRIPTION
**Pull request by peol**

### CODE REVIEW

**Comment by peol** [comment]
Before:

screen shot 2018-11-05 at 17 28 56

After (SEO is 100%, netlify sets a header on CI builds causing it to go lower):

screen shot 2018-11-05 at 17 28 25

**Comment by hrigner** [comment]
The 'x' might be a bit small?

**Comment by hrigner** [comment]
screen shot 2018-11-05 at 18 48 20

**Comment by peol** [comment]
I fix! I'll rebase your PR into this one first :)

**Comment by peol** [comment]
Material icons are removed in this PR, see below for the replacement and let me know if I should explore other "X":s.

screen shot 2018-11-06 at 09 39 53

**Pull request merged**
